export { PLUGIN_NAME } from "./version"
export const LEGACY_PLUGIN_NAME = "oh-my-openagent"
export const OPENCODE_PLUGIN_NAME = "oh-my-openagent"
export const OPENCODE_LEGACY_PLUGIN_NAME = "oh-my-magento"
export const CONFIG_BASENAME = "oh-my-openagent"
export const FORMER_CONFIG_BASENAME = "oh-my-magento"
export const LEGACY_CONFIG_BASENAME = "oh-my-openagent"
export const LOG_FILENAME = "oh-my-magento.log"
export const CACHE_DIR_NAME = "oh-my-magento"
